variables:
  SAST_EXCLUDED_ANALYZERS: "semgrep-sast,gosec-sast"
  DOCKER_DRIVER: overlay2

include:
  - template: Security/SAST.gitlab-ci.yml
  - local: 'engine/.gitlab-ci.yml'
  - local: 'ui/.gitlab-ci.yml'
