# Conditions.
.only_ui_feature: &only_ui_feature
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - ui/**/*

.only_ui_tag_release: &only_ui_tag_release
  rules:
    - if: $CI_COMMIT_TAG =~ /^ui\/[0-9.]+$/

# Jobs templates.
.build_definition: &build_definition
  image: docker:20.10.12
  stage: build
  services:
    - docker:dind
  script:
    - apk add --no-cache bash
    - bash ./ui/packages/ce/ci_docker_build_push.sh

# Jobs.
ui_build_ce_image_release:
  <<: *build_definition
  <<: *only_ui_tag_release
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_NAME: "postgresai/ce-ui"
  before_script:
    - export UI_VERSION=$(echo ${CI_COMMIT_TAG#"ui/"})
    - export TAGS="${DOCKER_NAME}:${UI_VERSION},${DOCKER_NAME}:latest"

ui_build_ce_image_dev:
  <<: *build_definition
  <<: *only_ui_feature
  variables:
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/ce-ui"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_REF_SLUG}"
  when: manual
